baseurl = "http://gopher-net.github.io/"
languageCode = "en-us"
title = "Network Gophers"
contentdir = "content"
layoutdir = "layouts"
publishdir = "."
canonifyurl =  true
theme = "hyde"

[params]
    description = "Your guide to Golang, Networking and Automation" 
    copyright = "2015-2016, CC-BY-SA 4.0"
    themeColor = "theme-base-0d"

[[menu.main]]
    name = "Blog"
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "Projects"
    identifier = "projects"
    url = "/projects/"
[[menu.main]]
    name = "Tutorials"
    identifier = "tutorials"
    url = "/tutorials/"
